repos:
  - repo: local
    hooks:
      - id: generate-changelog
        name: Generate changelog
        entry: .venv/bin/git-cliff -o CHANGELOG.md
        language: system
        pass_filenames: false
        stages: [pre-commit]
